# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

release_group: null

# Reference to one or more secrets to be used when pulling images
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# - name: orc8r-secrets-registry

# Define which secrets should be mounted by pods.
secret:
  certs: orc8r-certs

# magmalte
magmalte:
  create: true
  manifests:
    secrets: true
    deployment: true
    service: true
    rbac: true
  
  env:
    api_host: orc8r-proxy:9443
    host: 0.0.0.0
    port: 8081
    mapbox_access_token: ""
    mysql_host: mariadb
    mysql_db: magma
    mysql_user: magma
    mysql_pass: password
    mysql_dialect: mysql

  labels:
    node_selector_key: worker-type
    node_selector_value: controller

  image:
    repository:
    tag: latest
    pullPolicy: Always

  deployment:
    spec:
      operator_cert_name: admin_operator.pem
      operator_key_name: admin_operator.key.pem

  service:
    type: ClusterIP
    http:
      port: 8081
      targetport: 8081
      nodePort: ""

  tolerations: []
  affinity: {}

# nginx-Proxy
nginxserviceloadBalancerIP: ""
nginx:
  create: true
  manifests:
    configmap: true
    secrets: true
    deployment: true
    service: true
    rbac: true

  labels:
    node_selector_key: worker-type
    node_selector_value: controller

  image:
    repository: nginx
    tag: latest
    pullPolicy: Always

  service:
    type: LoadBalancer
    annotations: {}
    https:
      port: 443
      targetport: 443
      nodePort: ""

  deployment:
    spec:
      ssl_cert_name: controller.crt
      ssl_cert_key_name: controller.key

  tolerations: []
  affinity: {}

# POD Resource
pod:
  replicas:
    nginx:
      server: 1
    magmalte:
      server: 1
  resources:
    enabled: False
    nginx:
      requests:
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
    magmalte:
      requests:
        memory: "1024Mi"
        cpu: "100m"
      limits:
        memory: "2048Mi"
        cpu: "2000m"
