apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-magma-master-es-magma-master-0
  namespace: magma
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-nfs-storage
