apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-elasticsearch-master-0
  namespace: magma
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: managed-nfs-storage
