clusterName: "es-magma"
replicas: 2
clusterHealthCheckParams: 'wait_for_status=green&timeout=1s'
minimumMasterNodes: 1

# roles:
#   master: "true"
#   ingest: "true"
#   data: "true"
#   remote_cluster_client: "true"

image: "docker.elastic.co/elasticsearch/elasticsearch"
imageTag: "8.0.0-SNAPSHOT"
imagePullPolicy: "IfNotPresent"

resources:
  requests:
    cpu: "1000m"
    memory: "2Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

networkHost: "0.0.0.0"

rbac:
  create: true

antiAffinity: "soft"

service:
  type: LoadBalancer
  httpPortName: http
  annotations:
    external-dns.alpha.kubernetes.io/hostname: elasticsearch-client.magma.test

# volumeClaimTemplate:
#   accessModes: [ "ReadWriteOnce" ]
#   resources:
#     requests:
#       storage: 4Gi

data:
  # name: data
  # replicas: 1
  # persistence:
  #   enabled: true
  #   accessMode: ReadWriteOnce
  #   name: data
  #   size: "30Gi"
  storageClass: managed-nfs-storage

master:
  # name: master
  # replicas: 1
  # persistence:
  #   enabled: true
  #   accessMode: ReadWriteOnce
  #   name: data
  #   size: "4Gi"
  storageClass: managed-nfs-storage

  # nodeAffinity: {}
  # nodeSelector: {}
  # tolerations: []
  # initResources: {}
  # updateStrategy:
  #   type: OnDelete