image: "docker.elastic.co/kibana/kibana"
imageTag: "8.0.0-SNAPSHOT"
imagePullPolicy: "IfNotPresent"

elasticsearchHosts: "http://elasticsearch-master:9200"

extraEnvs:
  - name: "LOGGING_VERBOSE"
    value: "false"

resources:
  requests:
    cpu: "2000m"
    memory: "4Gi"
  limits:
    cpu: "2000m"
    memory: "4Gi"

protocol: http

serverHost: "0.0.0.0"

service:
  type: LoadBalancer
  port: 5601
  nodePort: ""
  labels: {}
  annotations: {}
  httpPortName: http

files:
  kibana.yml:
    ## Default Kibana configuration from kibana-docker.
    server.name: kibana
    server.host: "0.0.0.0"
    elasticsearch.hosts: "http://elasticsearch-master:9200"
    # elasticsearch.requestTimeout: 30000

dashboardImport:
  enabled: true
  timeout: 60
  dashboards:
    k8s: https://raw.githubusercontent.com/monotek/kibana-dashboards/master/k8s-fluentd-elasticsearch.json