apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-elasticsearch-data-0
  namespace: magma
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  storageClassName: managed-nfs-storage
