apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configs
  namespace: magma
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-nfs-storage
